// Copyright (C) 2018, Jaguar Land Rover
// This program is licensed under the terms and conditions of the
// Mozilla Public License, version 2.0.  The full text of the 
// Mozilla Public License is at https://www.mozilla.org/MPL/2.0/
//
// Author: Magnus Feuer (mfeuer1@jaguarlandrover.com)


#ifndef __DSTC_H__
#define __DSTC_H__
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include "reliable_multicast/reliable_multicast.h"


typedef struct  __attribute__((packed))
dstc_header {
    uint16_t payload_len;          // 2
    rmc_node_id_t node_id;         // 4 bytes  Publisher Node ID
    uint32_t trans_id;             // 4 bytes of transaction ID. 0 for signals
    uint8_t name_len;              // 1 byte of name length
    uint8_t payload[];             // Function name
} dstc_header_t;

extern uint32_t dstc_get_socket_count(void);
extern int dstc_get_next_timeout(usec_timestamp_t* result_ts);
extern int dstc_setup(void);
extern int dstc_setup_epoll(int epollfd);
extern int dstc_process_events(usec_timestamp_t timeout);
extern void dstc_process_timeout(void);
extern int dstc_get_timeout_msec(void);
extern uint32_t dstc_get_remote_count(char* function_name);
extern usec_timestamp_t dstc_get_timeout_timestamp(void);
struct epoll_event;
extern int dstc_process_single_event(int timeout);
extern void dstc_process_epoll_result(struct epoll_event* event);
extern rmc_node_id_t dstc_get_node_id(void);

// FIXME: ADD DOCUMENTATION
typedef struct {
    uint32_t length;
    void* data;
} dstc_dynamic_data_t;

// Setup a simple macro so that we don't need an extra comma
// when we use DECL_DYNAMIC_ARG in DSTC_CLIENT and DSTC_SERVER lines.
#define DECL_DYNAMIC_ARG DSTC,

// Tag for dynamic data magic cookie: "DSTC" = 0x44535443
// Used by DESERIALIZE_ARGUMENT and SERIALIZE_ARGUMENT
// to detect dynamic data arguments
#define DSTC_DYNARG_TAG 0x44535443

// Define an alias type that matches the magic cookie.
typedef dstc_dynamic_data_t DSTC;

// Use dynamic arguments as:
// dstc_send_variable_len(DYNARG("Hello world", 11))
#define DYNAMIC_ARG(_data, _length) ({ DSTC d = { .length = _length, .data = _data }; d; })

// Tag for function pointer argument. "CBCK" = 0x4342434B
// Used by DESERIALIZE_ARGUMENT and SERIALIZE_ARGUMENT
// to detect callback function arguments
#define DSTC_CALLBACK_TAG 0x4342434B

typedef struct {
    rmc_node_id_t node_id; // Used by callback to target the originating process
    uint8_t name_len;      // Number of bytes in the callback function
    uint8_t* callback_func; // Function name
} dstc_callback_t;

// Setup a simple macro so that we don't need an extra comma
// when we use DECL_CALLBACK_ARG in DSTC_CLIENT and DSTC_SERVER lines.
#define DECL_CALLBACK_ARG CBCK, 

// Define an alias type that matches the magic cookie.
typedef dstc_callback_t CBCK;


#define CALLBACK_ARG(_func_name) ({              \
            CBCK callback = {                    \
                .name_len = strlen(#_func_name), \
                .node_id = dstc_get_node_id(),   \
                .func_name = #_func_name         \
            };                                   \
            callback;                            \
        })

// Thanks to https://codecraft.co/2014/11/25/variadic-macros-tricks for
// deciphering variadic macro iterations.
// Return argument N.
#define _GET_NTH_ARG(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10,   \
                     _11, _12, _13, _14, _15, _16, N, ...) N

#define _GET_ARG_COUNT(...) _GET_NTH_ARG(__VA_ARGS__, 16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1)

// Smells like... Erlang!
#define _FE0(_call)
#define _FE2(_call, type, size, ...) _call(1, type, size) 
#define _FE4(_call, type, size, ...) _call(2, type, size) _FE2(_call, __VA_ARGS__)
#define _FE6(_call, type, size, ...) _call(3, type, size) _FE4(_call, __VA_ARGS__)
#define _FE8(_call, type, size, ...) _call(4, type, size) _FE6(_call, __VA_ARGS__)
#define _FE10(_call, type, size, ...) _call(5, type, size) _FE9(_call, __VA_ARGS__)
#define _FE12(_call, type, size, ...) _call(6, type, size) _FE11(_call, __VA_ARGS__)
#define _FE14(_call, type, size, ...) _call(7, type, size) _FE14(_call, __VA_ARGS__)
#define _FE16(_call, type, size, ...) _call(8, type, size) _FE16(_call, __VA_ARGS__)
#define _ERR(...) "Declare arguments in pairs: (char, [16]). Leave size empty if not array (int,)"

#define FOR_EACH_VARIADIC_MACRO(_call, ...)                             \
    _GET_NTH_ARG(__VA_ARGS__,                                           \
                 _FE16, _ERR, _FE14, _ERR,                              \
                 _FE12, _ERR, _FE10, _ERR,                              \
                 _FE8,  _ERR, _FE6,  _ERR,                              \
                 _FE4,  _ERR, _FE2,  _ERR, _FE0)(_call, ##__VA_ARGS__)  

// List building variant where each output generated by _call(),
// except the last one, is trailed by a comma.
// Solves trailing comma issue
#define _LE2(_call, type, size, ...) _call(1, type, size) 
#define _LE4(_call, type, size, ...) _call(2, type, size) , _LE2(_call, __VA_ARGS__)
#define _LE6(_call, type, size, ...) _call(3, type, size) , _LE4(_call, __VA_ARGS__)
#define _LE8(_call, type, size, ...) _call(4, type, size) , _LE6(_call, __VA_ARGS__)
#define _LE10(_call, type, size, ...) _call(5, type, size) , _LE8(_call, __VA_ARGS__)
#define _LE12(_call, type, size, ...) _call(6, type, size) , _LE10(_call, __VA_ARGS__)
#define _LE14(_call, type, size, ...) _call(7, type, size) , _LE12(_call, __VA_ARGS__)
#define _LE16(_call, type, size, ...) _call(8, type, size) , _LE14(_call, __VA_ARGS__)

#define FOR_EACH_VARIADIC_MACRO_ELEM(_call, ...)                        \
    _GET_NTH_ARG(__VA_ARGS__,                                           \
                 _LE16, _ERR, _LE14, _ERR,                              \
                 _LE12, _ERR, _LE10, _ERR,                              \
                 _LE8,  _ERR, _LE6,  _ERR,                              \
                 _LE4,  _ERR, _LE2,  _ERR, _LE0)(_call, ##__VA_ARGS__)  

// replace if with switch?
#define SERIALIZE_ARGUMENT(arg_id, type, size)                          \
    switch(*(uint32_t*) #type) {                                       \
    case DSTC_DYNARG_TAG:                                               \
        *((uint32_t*) data) = ((dstc_dynamic_data_t*) &_a##arg_id)->length; \
        data += sizeof(uint32_t);                                       \
        memcpy((void*) data, ((dstc_dynamic_data_t*) &_a##arg_id)->data, \
               ((dstc_dynamic_data_t*) & _a##arg_id)->length);          \
        data += ((dstc_dynamic_data_t*) & _a##arg_id)->length;          \
        break;                                                          \
                                                                        \
    case DSTC_CALLBACK_TAG:                                             \
        *((rmc_node_id_t*) data) = ((dstc_callback_t*) &_a##arg_id)->node_id; \
        data += sizeof(rmc_node_id_t);                                    \
        *data = ((dstc_callback_t*) &_a##arg_id)->name_len;             \
        data++;                                                         \
        memcpy((void*) data, ((dstc_callback_t*) &_a##arg_id)->callback_func, \
               ((dstc_callback_t*) &_a##arg_id)->name_len);         \
        data += ((dstc_callback_t*) & _a##arg_id)->name_len;        \
        break;                                                          \
                                                                        \
    default:                                                            \
        if (sizeof(type size ) == sizeof(type))                         \
            memcpy((void*) data, (void*) &_a##arg_id, sizeof(type size)); \
        else                                                            \
            memcpy((void*) data, (void*) *(char**) &_a##arg_id, sizeof(type size)); \
        data += sizeof(type size);                                      \
    }


#define DESERIALIZE_ARGUMENT(arg_id, type, size)                        \
    switch(*(uint32_t*) #type) {                                        \
    case DSTC_DYNARG_TAG:                                               \
        ((dstc_dynamic_data_t*) &_a##arg_id)->length = *((uint32_t*) data); \
        data += sizeof(uint32_t);                                       \
        ((dstc_dynamic_data_t*) &_a##arg_id)->data = data;              \
        data += ((dstc_dynamic_data_t*) &_a##arg_id)->length;           \
        break;                                                          \
                                                                        \
    case DSTC_CALLBACK_TAG:                                             \
        ((dstc_callback_t*) &_a##arg_id)->node_id = ((dstc_callback_t*) data)->node_id; \
        data += sizeof(rmc_node_id_t);                                    \
        ((dstc_callback_t*) &_a##arg_id)->name_len = ((dstc_callback_t*) data)->name_len; \
        data++;                                                         \
        memcpy(((dstc_callback_t*) &_a##arg_id)->callback_func, data,   \
               ((dstc_callback_t*) &_a##arg_id)->name_len);             \
        data += ((dstc_callback_t*) &_a##arg_id)->name_len;             \
        break;                                                          \
                                                                        \
    default:                                                            \
        if (sizeof(type size) == sizeof(type))                          \
            memcpy((void*) &_a##arg_id, (void*) data, sizeof(type size)); \
        else                                                            \
            memcpy((void*) (uint32_t*) &_a##arg_id, (void*) data, sizeof(type size)); \
        data += sizeof(type size);                                      \
    }

#define DECLARE_ARGUMENT(arg_id, type, size) type _a##arg_id size
#define LIST_ARGUMENT(arg_id, type, size) _a##arg_id
#define DECLARE_VARIABLE(arg_id, type, size) type _a##arg_id size ;
#define SIZE_ARGUMENT(arg_id, type, size) ((* (uint32_t*) #type == DSTC_DYNARG_TAG)?(sizeof(uint32_t) + ((dstc_dynamic_data_t*) &_a##arg_id)->length): sizeof(type size)) +

#define SERIALIZE_ARGUMENTS(...) FOR_EACH_VARIADIC_MACRO(SERIALIZE_ARGUMENT, ##__VA_ARGS__)
#define DESERIALIZE_ARGUMENTS(...) FOR_EACH_VARIADIC_MACRO(DESERIALIZE_ARGUMENT, ##__VA_ARGS__)
#define DECLARE_ARGUMENTS(...) FOR_EACH_VARIADIC_MACRO_ELEM(DECLARE_ARGUMENT, ##__VA_ARGS__)
#define LIST_ARGUMENTS(...) FOR_EACH_VARIADIC_MACRO_ELEM(LIST_ARGUMENT, ##__VA_ARGS__)
#define DECLARE_VARIABLES(...) FOR_EACH_VARIADIC_MACRO(DECLARE_VARIABLE, ##__VA_ARGS__)
#define SIZE_ARGUMENTS(...) FOR_EACH_VARIADIC_MACRO(SIZE_ARGUMENT, ##__VA_ARGS__) 0


// Create client function that serializes and writes to descriptor.
// If the reliable multicast system has not been started when the
// client call is made, it is will be done through dstc_setup()
#define DSTC_CLIENT(name, ...)                                   \
    void dstc_##name(DECLARE_ARGUMENTS(__VA_ARGS__)) {                  \
        uint32_t arg_sz = SIZE_ARGUMENTS(__VA_ARGS__);                  \
        uint8_t arg_buf[arg_sz];                                        \
        uint8_t *data = arg_buf;                                        \
        extern void _dstc_queue(uint8_t* name, uint8_t* arg_buf, uint32_t arg_sz); \
                                                                        \
        SERIALIZE_ARGUMENTS(__VA_ARGS__);                               \
        _dstc_queue(#name, arg_buf, arg_sz);                            \
    }                                                                   \

#define _DSTC_AUTO_REGISTER(name)                                       \
    void __attribute__((constructor)) _dstc_register_##name()           \
    {                                                                   \
        extern void dstc_register_local_function(char*, void (*)(rmc_node_id_t, uint32_t, uint8_t*)); \
        dstc_register_local_function(#name, dstc_server_##name);        \
    }                                                                   \


// Generate server function that receives serialized data on
// descriptor and invokes he local function.
// If the socket has not been setup when the client call is made,
// it is will be done through dstc_net_client.c:dstc_setup_mcast_sub() 
#define DSTC_SERVER_INTERNAL(name, ...)                                 \
    void dstc_server_##name(rmc_node_id_t node_id, uint32_t trans_id, uint8_t* data) \
    {                                                                   \
        DECLARE_VARIABLES(__VA_ARGS__);                                 \
        DESERIALIZE_ARGUMENTS(__VA_ARGS__);                             \
        name(LIST_ARGUMENTS(__VA_ARGS__));                              \
        return;                                                         \
    }                                                                   \

#define DSTC_SERVER(name, ...)                          \
    extern void name(DECLARE_ARGUMENTS(__VA_ARGS__));   \
    static DSTC_SERVER_INTERNAL(name, __VA_ARGS__)      \
    static _DSTC_AUTO_REGISTER(name)

#endif // __DSTC_H__


