// Copyright (C) 2018, Jaguar Land Rover
// This program is licensed under the terms and conditions of the
// Mozilla Public License, version 2.0.  The full text of the 
// Mozilla Public License is at https://www.mozilla.org/MPL/2.0/
//
// Author: Magnus Feuer (mfeuer1@jaguarlandrover.com)
//
// Running example code from README.md in https://github.com/PDXOSTC/dstc
//

#include <stdio.h>
#include <stdlib.h>
#include "dstc.h"

DSTC_SERVER(dynamic_message, DECL_DYNAMIC_ARG)

//
// Print out name and age.
// Invoked by deserilisation code generated by DSTC_SERVER() above.
// Please note that the arguments must match between the function below
// and the macro above.
//
void dynamic_message(dstc_dynamic_data_t dynarg)
{
    printf("Data:   %*s\n", dynarg.length, (char*) dynarg.data);
    printf("Length: %d\n", dynarg.length);
}

int main(int argc, char* argv[])
{
    while(1) {
        dstc_read();
    }
        
    exit(0);
}


