# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_dstc_swig')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_dstc_swig')
    _dstc_swig = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dstc_swig', [dirname(__file__)])
        except ImportError:
            import _dstc_swig
            return _dstc_swig
        try:
            _mod = imp.load_module('_dstc_swig', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _dstc_swig = swig_import_helper()
    del swig_import_helper
else:
    import _dstc_swig
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def register_python_server_function(name):
    return _dstc_swig.register_python_server_function(name)
register_python_server_function = _dstc_swig.register_python_server_function

def set_python_callback(cb):
    return _dstc_swig.set_python_callback(cb)
set_python_callback = _dstc_swig.set_python_callback

def register_client_function(name):
    return _dstc_swig.register_client_function(name)
register_client_function = _dstc_swig.register_client_function

def dstc_setup():
    return _dstc_swig.dstc_setup()
dstc_setup = _dstc_swig.dstc_setup

def dstc_process_events(arg1):
    return _dstc_swig.dstc_process_events(arg1)
dstc_process_events = _dstc_swig.dstc_process_events

def dstc_queue_func(name, arg, arg_sz):
    return _dstc_swig.dstc_queue_func(name, arg, arg_sz)
dstc_queue_func = _dstc_swig.dstc_queue_func

def dstc_remote_function_available_by_name(func_name):
    return _dstc_swig.dstc_remote_function_available_by_name(func_name)
dstc_remote_function_available_by_name = _dstc_swig.dstc_remote_function_available_by_name
# This file is compatible with both classic and new-style classes.


