// Copyright (C) 2018, Jaguar Land Rover
// This program is licensed under the terms and conditions of the
// Mozilla Public License, version 2.0.  The full text of the
// Mozilla Public License is at https://www.mozilla.org/MPL/2.0/
//
// Author: Magnus Feuer (mfeuer1@jaguarlandrover.com)
//
// Running example code from README.md in https://github.com/PDXOSTC/dstc
//

#include <stdio.h>
#include <stdlib.h>
#include "dstc.h"
#include "rmc_log.h"
#include <errno.h>

// Generate deserializer for multicast packets sent by dstc_message()
// above.
// The deserializer decodes the incoming data and calls the
//  doule_value() function in this file.
//
DSTC_SERVER(double_value, int,, DSTC_DECL_CALLBACK_ARG)


//
// Print out name and age.
// Invoked by deserilisation code generated by DSTC_SERVER() above.
// Please note that the arguments must match between the function
// below and the macro above.
//
// The funtiuon argument callback_ref is provided as the first
// argument to DSTC_CALLBACK().
// The DSTC_CALLBACK() macro generates a local function called
// dstc_[name] where name is the name of the callback reference,
// (callback_ref in the example below).
//
DSTC_SERVER_CALLBACK(callback_ref, int,);
void double_value(int value, dstc_callback_t callback_ref)
{
    static int nil_callback_invoked = 0;

    if (value == -1) {
        puts("double_value(-1): Got exit signal.");
        while(dstc_process_events(0) != ETIME)
            ;

        if (!nil_callback_invoked) {
            puts("double_value() with a nil callback reference was never invoked by the client");
            exit(255);
        }

        exit(0);
    }


    // Check if this is a nil callback ref.
    // In this case we will just note that it was received and continue
    // to process the callback as per usual.
    // dstc_callback_ref() below will trigger on that callback_ref is
    // 0 and return success immediately without sending any data to
    // the client.

    if (!callback_ref) {
        printf("double_value(%d) called with a null callback. Good\n", value);
        nil_callback_invoked = 1;
    } else
        printf("double_value(%d) called with a callback. Good\n", value);

    // Callback will return ENOENT if the client was started before
    // the server and calls double_value() before all connections
    // are setup. In these cases process a few events until we get the
    // connection

    while(dstc_callback_ref(callback_ref, value + value) == ENOENT) {
        puts("Waiting for the client connection to complete.");
        dstc_process_events(50);
    }

    // Process events until we have emptied the queue.
    while(dstc_process_events(0) != ETIME);
    exit(0);
}

int main(int argc, char* argv[])
{
    // Process incoming events for ever
    while(1)
        dstc_process_events(-1);

    exit(0);
}
