all:
	(cd chat; make)
	(cd print_name_and_age; make)
	(cd dynamic_data; make)
	(cd struct; make)

clean:
	(cd chat; make clean)
	(cd print_name_and_age; make clean)
	(cd dynamic_data; make clean)
	(cd struct; make clean)
